name: remote ssh command
on:
  workflow_call:
    secrets:
      HOST: 
        required: true
      USERNAME: 
        required: true
      KEY:
        required: true
      PORT:
        required: true
      DOTENV_PRIVATE_KEY:
        required: true
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Setting up environment
        uses: appleboy/ssh-action@v1.1.0
        env:
          REPO:  ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: REPO, OWNER
          script:  |
            mkdir $OWNER
            cd $OWNER
            git clone https://github.com/$REPO.git
            cd ~/$REPO
            git checkout release
            git reset --hard HEAD
            git pull
  build:
    needs:  setup
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Building Docker Compose
        id: build
        uses: appleboy/ssh-action@v1.1.0
        env:
          REPO: ${{ github.repository }}
          DOTENV_PRIVATE_KEY: ${{secrets.DOTENV_PRIVATE_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: REPO, DOTENV_PRIVATE_KEY
          script: |
            cd ~/$REPO
            echo "#.env" > .env.keys
            echo "DOTENV_PRIVATE_KEY=\"$DOTENV_PRIVATE_KEY\"" >> .env.keys
            docker compose build
      - name: Executing Docker Compose 
        if: steps.build.outcome == 'success'
        uses: appleboy/ssh-action@v1.1.0
        env:
          REPO: ${{ github.repository }}
          DOTENV_PRIVATE_KEY: ${{secrets.DOTENV_PRIVATE_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: REPO, DOTENV_PRIVATE_KEY
          script: |
            cd ~/$REPO
            docker compose down
            docker compose up -d
